### ISSUE TITLE
Can't install the file using pip

### ISSUE THREAD

**Issue by nomustfc** [datstat-consulting/PanelKalmanFilter#1]
Sorry to bother you. I am new to Python, and I tried to install the file using pip but it says that your file doesn't seem to be a Python project: "neither 'setup.py' nor 'pyproject.toml' found."
I wonder if there is anything you can do to help me.
Best.

**Comment by datstat-consulting** [comment]
For now, just download the class manually. We're new to making Python packages.

**Comment by datstat-consulting** [comment]
added a pyproject.toml file, installation through pip now works

**Comment by nomustfc** [comment]
thank you so much for your reply. I will try again.
