### ISSUE TITLE
wrapMinimize() missing 1 required positional argument: 'self'

### ISSUE THREAD

**Issue by nomustfc** [datstat-consulting/PanelKalmanFilter#3]
Sorry to interupt again.
I was running the following code as your md file suggested in Jupyter:
   "params_init = pkf.paramInit()
    MLE = wrapMinimize(params_init = params_init, algo = 'BFGS')"
But it shows "wrapMinimize() missing 1 required positional argument: 'self'"
I didn't know how to fix it. Is there anything you can do to help? Again, sorry for my poor code abilities.

Best.

**Comment by datstat-consulting** [comment]
That should be `pkf.wrapMinimize(params_init = params_init, algo = 'BFGS')`, will update the readme

**Comment by nomustfc** [comment]
Thank you for your help! Have a nice day!

Datstat Consulting ***@***.***>于2023年11月20日 周一22:47写道：
